const PushNotificationController = require('../controllers/push.notification.controller');
const AuthGuard = require('../config/authguard');

module.exports = function(router, validateRoutes, validateAuth,validateContentType)
{
    /**
     * 
     * @api {post} /push/subscribe Push Subscribe
     * @apiName PushSubscribe
     * @apiGroup Push
     * @apiVersion  1.0.0
     * @apiDescription Check web-push documentation for more detail
     * 
     * @apiParam  {String} subscription JSON string generated by ServiceWorker converted with urlBase64ToUint8Array
     * 
     * @apiSuccess (Response: 200) {Boolean} success Response status
     * 
     * @apiSuccessExample {Object} Success-Response:
     * {
     *     success : true
     * }
     * 
     */
    router.post('/push/subscribe',validateRoutes, PushNotificationController.subscribe);

}